### PR TITLE
Put downstream files directly to SPECS & SOURCES

### PR DESCRIPTION
**Pull request by jpopelka**
Instead of into `centos-packaging/SPECS` & `centos-packaging/SOURCES`.

Howto test:
```
$ make convert
$ cd git.centos.org/src/rpm
$ ls SPECS/
$ git log
```

### CODE REVIEW

**Comment by sakalosj** [comment]
LGTM
@TomasTomecek, can you also check

**Comment by TomasTomecek** [comment]
doesn't werk buddy

```
$ m convert
rm -rf git.centos.org/                                                                                                                                                       
git clone https://git.centos.org/rpms/rpm.git git.centos.org/rpms/rpm
Cloning into 'git.centos.org/rpms/rpm'...                                             
remote: Counting objects: 302, done.                                                  
remote: Compressing objects: 100% (276/276), done.
remote: Total 302 (delta 34), reused 226 (delta 0)
Receiving objects: 100% (302/302), 276.90 KiB | 668.00 KiB/s, done.
Resolving deltas: 100% (34/34), done.                                                 
warning: remote HEAD refers to nonexistent ref, unable to checkout.                                                                                                          
                                                                                                                                                                             
./dist2src.py  convert git.centos.org/rpms/rpm:c8s git.centos.org/src/rpm:c8s                                                                                                
Traceback (most recent call last):
  File "./dist2src.py", line 343, in <module>
    cli()
  File "/usr/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "./dist2src.py", line 71, in wrapper 
    ret = func(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "./dist2src.py", line 334, in convert
    ctx.invoke(get_archive, gitdir=origin_dir)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "./dist2src.py", line 71, in wrapper 
    ret = func(*args, **kwargs)
  File "./dist2src.py", line 123, in get_archive
    command = sh.Command(script)
  File "/usr/lib/python3.8/site-packages/sh.py", line 1202, in __init__
    raise CommandNotFound(path)
sh.CommandNotFound: get_sources.sh
make: *** [Makefile:22: convert] Error 1
```

**Comment by TomasTomecek** [comment]
also please add "sh" to Pipfile, had to install it additionally

**Comment by jpopelka** [comment]
I think you need https://wiki.centos.org/Sources#get_sources.sh_script

**Comment by TomasTomecek** [comment]
@_@

could we get a note about it to readme?

**Comment by jpopelka** [comment]
> should I update the README

please do, thanks!

**Pull request merged**
